#!/bin/bash

echo "=== Locus Complete Setup Guide ==="
echo ""
echo "Your Workspace Status:"
echo "  Email: anandcollege07@gmail.com"
echo "  Balance: $1.00 USDC"
echo "  Status: Active"
echo ""

echo "Step 1: Get Your API Key"
echo "  1. Go to: https://app.paywithlocus.com"
echo "  2. Login with: anandcollege07@gmail.com"
echo "  3. Click 'API Key' in sidebar"
echo "  4. Click 'Generate API Key'"
echo "  5. Copy the key (starts with claw_dev_)"
echo ""

echo "Step 2: Test Your API Key"
echo "  Replace YOUR_KEY below with your actual API key:"
echo ""
echo "  curl -X POST https://api.paywithlocus.com/api/pay/balance \\"
echo "    -H \"Authorization: Bearer YOUR_KEY\""
echo ""

echo "Step 3: Configure API Hacker Agent"
echo "  1. Open: http://localhost:3000"
echo "  2. Click 'Connect Locus' (indigo button)"
echo "  3. Paste your API key"
echo "  4. Click 'Connect Workspace'"
echo ""

echo "Step 4: Test Real Execution"
echo "  Try this task:"
echo "    Task: 'Summarize the latest AI trends'"
echo "    Budget: $0.10"
echo ""

echo "Step 5: Configure Spending Controls (Optional)"
echo "  In your Locus dashboard, set:"
echo "  - Allowance: Maximum total USDC"
echo "  - Max transaction: Cap per transaction"
echo "  - Approval threshold: Manual approval for large amounts"
echo ""

echo "Current Setup Files Created:"
echo "  - ~/.config/locus/credentials.json (template)"
echo "  - API Hacker Agent ready for connection"
echo ""

echo "Next Actions:"
echo "  1. Get your API key from the dashboard"
echo "  2. Test it with the curl command"
echo "  3. Connect the API Hacker Agent"
echo "  4. Execute real tasks with your $1.00 USDC"
echo ""

echo "Documentation:"
echo "  - https://paywithlocus.com/skill.md"
echo "  - https://docs.paywithlocus.com"
echo "  - https://mpp.sh/services (89 available endpoints)"
echo ""

echo "=== Ready for Complete Setup ==="
